Repository brefphp/bref, pull requests merged in 2018-11, with the labels that each got.

#74 adding path option in InvokeCommand
  src/Cli/InvokeCommand.php
  tests/Cli/InvokeCommandTest.php
Labels: enhancement

#83 Allow specifying event data with `bref invoke`
  README.md
  bref
Labels: enhancement

#82 Fix missing syntax highlighting
  docs/Symfony.md
Labels: documentation

#84 Fix Laravel header forwarding
  src/Bridge/Laravel/LaravelAdapter.php
  tests/Bridge/Laravel/LaravelAdapterTest.php
Labels: bug

#85 Fix Laravel's `runningInConsole()` on AWS Lambda
  docs/Laravel.md
  src/Bridge/Laravel/Application.php
  tests/Bridge/Laravel/ApplicationTest.php
  tests/Bridge/Laravel/LaravelAdapterTest.php
Labels: bug

#91 Add default maximum concurrency setting
  template/serverless.yml
Labels: enhancement

#98 Setup stricter code quality tools
  .gitignore
  .php_cs
  .phpcs.xml.dist
  .prettyci.composer.json
  .travis.yml
  bref
  composer.json
  phpstan.neon.dist
  src/Application.php
  src/Bridge/Laravel/Application.php
  src/Bridge/Laravel/LaravelAdapter.php
  src/Bridge/Psr7/RequestFactory.php
  src/Bridge/Slim/SlimAdapter.php
  src/Bridge/Symfony/SymfonyAdapter.php
  src/Cli/InvokeCommand.php
  src/Cli/WelcomeApplication.php
  src/Console/Deployer.php
  src/Filesystem/DirectoryMirror.php
  src/Http/LambdaResponse.php
  src/Http/WelcomeHandler.php
  src/functions.php
  template/bref.php
  tests/Bridge/Laravel/ApplicationTest.php
  tests/Bridge/Laravel/LaravelAdapterTest.php
  tests/Bridge/Laravel/config/app.php
  tests/Bridge/Psr7/RequestFactoryTest.php
  tests/Bridge/Slim/SlimAdapterTest.php
  tests/Bridge/Symfony/SymfonyAdapterTest.php
  tests/Cli/InvokeCommandTest.php
  tests/CliTest.php
  tests/Http/LambdaResponseTest.php
  tests/JsHandler/JsHandlerTest.php
  tests/JsHandler/bref.array-response.php
  tests/JsHandler/bref.error.php
  tests/JsHandler/bref.read-event.php
  tests/JsHandler/bref.stderr.php
  tests/JsHandler/bref.stdout.php
Labels: enhancement
