Repository brefphp/bref, pull requests merged in 2018-08, with the labels that each got.

#53 Add missing stage option
  bref
Labels: enhancement

#56 Fix arrays handling in query string
  src/Bridge/Psr7/RequestFactory.php
  tests/Bridge/Psr7/RequestFactoryTest.php
Labels: bug

#57 Add example for framework-less HTTP application
  README.md
Labels: documentation
