Repository brefphp/bref, pull requests merged in 2019-03, with the labels that each got.

#257 Try to fix #220: recover from timeouts
  runtime/php/layers/fpm/bootstrap
  src/Runtime/FastCgiCommunicationFailed.php
  src/Runtime/LambdaRuntime.php
  src/Runtime/PhpFpm.php
  template.yaml
  tests/Runtime/PhpFpm/php-fpm.conf
  tests/Runtime/PhpFpm/timeout.php
  tests/Runtime/PhpFpmTest.php
Labels: bug

#236 LambdaRuntime test
  src/Runtime/LambdaRuntime.php
  tests/Runtime/LambdaRuntimeTest.php
  tests/Server.php
  tests/server.js
Labels: enhancement

#258 Add a "maturity matrix" in the documentation
  docs/README.md
  website/tailwind.js
  website/template/styles.css
Labels: documentation

#266 Add a "community" page in the documentation
  couscous.yml
  docs/community.md
  website/_redirects
Labels: documentation

#272 Fix #265 Recover from Lambda timeouts
  demo/http.php
  phpstan.neon.dist
  runtime/php/layers/fpm/php-fpm.conf
  src/Runtime/PhpFpm.php
  template.yaml
  tests/Runtime/PhpFpmTest.php
Labels: bug

#273 phpstan update to 0.11
  composer.json
  phpstan.neon.dist
Labels: enhancement

#276 Add the PrettyCI case study
  docs/case-studies.md
Labels: documentation

#277 Document secret values in environment variables
  docs/environment/variables.md
Labels: documentation

#280 Recommend the `us-east-1` region when discovering Bref
  docs/installation.md
Labels: documentation

#285 add region choice during init
  bref
Labels: enhancement
