Repository brefphp/bref, pull requests merged in 2019-01, with the labels that each got.

#137 md instead of rst now
  docs/deploy.md
Labels: documentation

#135 Reorder docs to match each variable for the ARN
  docs/runtimes/README.md
Labels: documentation

#138 ensure the right transform is used?
  docs/runtimes/README.md
  docs/runtimes/console.md
Labels: documentation

#139 forgot a period at the end
  docs/README.md
Labels: documentation

#142 removing or replacing etc.
  docs/deploy.md
  docs/environment/logs.md
  docs/environment/storage.md
  docs/frameworks/laravel.md
  docs/frameworks/symfony.md
  docs/runtimes/README.md
  docs/runtimes/http.md
  tests/HttpRequestProxyTest.php
  website/tailwind.js
Labels: documentation

#141 keeping things consistent
  docs/local-development.md
Labels: documentation

#145 #144: Make publish scripts more portable
  runtime/console/publish.sh
  runtime/default/publish.sh
  runtime/fpm/publish.sh
  runtime/loop/publish.sh
Labels: bug

#147 Documentation: add a "First steps" guide and links to next/previous articles
  couscous.yml
  docs/README.md
  docs/first-steps.md
  docs/installation.md
  docs/runtimes/README.md
  docs/runtimes/console.md
  docs/runtimes/function.md
  docs/runtimes/http.md
  website/template/default.twig
Labels: documentation

#132 PHP Layer(s) Runtime Pipeline for v3.0
  runtime/experimental/.gitignore
  runtime/experimental/Makefile
  runtime/experimental/bootstraps/cli.bootstrap
  runtime/experimental/compiler.Dockerfile
  runtime/experimental/export.Dockerfile
  runtime/experimental/helpers/docker_args.php
  runtime/experimental/helpers/export.sh
  runtime/experimental/php.Dockerfile
  runtime/experimental/readme.md
  runtime/experimental/tests/default/.gitignore
  runtime/experimental/tests/default/Makefile
  runtime/experimental/tests/default/template.yaml.static
  runtime/experimental/tests/default/test.php
  runtime/experimental/versions.ini
Labels: enhancement

#157 Fix url to install AWS SAM CLI
  docs/installation.md
Labels: documentation

#155 Start merging the experimental build pipeline and the existing runtimes
  Makefile
  runtime/default/README.md
  runtime/default/build.sh
  runtime/default/publish.sh
  runtime/experimental/export.Dockerfile
  runtime/fpm/README.md
  runtime/fpm/build.sh
  runtime/fpm/publish.sh
  runtime/php/.gitignore
  runtime/php/Makefile
  runtime/php/compiler.Dockerfile
  runtime/php/export.Dockerfile
  runtime/php/helpers/docker_args.php
  runtime/php/helpers/publish.sh
  runtime/php/layers/cli.bootstrap
  runtime/php/layers/fpm/bootstrap
  runtime/php/layers/fpm/php-fpm.conf
  runtime/php/layers/fpm/php.ini
  runtime/php/layers/function/bootstrap
  runtime/php/layers/function/php.ini
  runtime/php/php.Dockerfile
  runtime/php/publish.php
  runtime/php/readme.md
  runtime/php/versions.ini
  src/Runtime/PhpFpm.php
Labels: enhancement

#170 Fix typo in Symfony doc
  docs/frameworks/symfony.md
Labels: documentation

#168 Website: show the latest versions of the runtimes
  docs/runtimes/README.md
Labels: documentation

#177 Make sure that the status code header is not returned in the response
  src/Runtime/PhpFpm.php
  tests/Runtime/PhpFpm/response-headers.php
  tests/Runtime/PhpFpmTest.php
Labels: bug

#179 remove 0.2-specific Symfony documentation & update for 0.3/SAM local
  docs/frameworks/symfony.md
Labels: documentation

#178 Automatically set the Content-Length header on POST requests
  src/Runtime/PhpFpm.php
  tests/Runtime/PhpFpm/request.php
  tests/Runtime/PhpFpmTest.php
Labels: bug

#182 Build all runtimes on all regions in a unified process
  Makefile
  runtime/.gitignore
  runtime/Makefile
  runtime/console/.gitignore
  runtime/console/README.md
  runtime/console/publish.sh
  runtime/export/.gitignore
  runtime/php/.gitignore
  runtime/php/Makefile
  runtime/php/helpers/publish.sh
  runtime/publish.php
Labels: enhancement

#188 #184 Log to CloudWatch in PHP-FPM by logging to stderr
  docs/environment/logs.md
  docs/frameworks/symfony.md
  runtime/php/layers/fpm/php-fpm.conf
  runtime/php/layers/fpm/php.ini
  src/Runtime/PhpFpm.php
  template.yaml
Labels: enhancement

#189 Simplify the script that builds the layers
  runtime/php/Makefile
  runtime/php/export.Dockerfile
  runtime/php/export.sh
Labels: enhancement

#193 Build PHP 7.3 runtimes
  docs/runtimes/README.md
  docs/runtimes/console.md
  docs/runtimes/function.md
  docs/runtimes/http.md
  runtime/php/Makefile
  runtime/php/export.sh
  runtime/php/php.Dockerfile
  runtime/php/versions.ini
  runtime/publish.php
  template/console/template.yaml
  template/default/template.yaml
  template/http/template.yaml
  website/tailwind.js
Labels: enhancement

#203 Enable Opcache and Zip. Remove unwanted binaries.
  .gitignore
  runtime/php/php.Dockerfile
  runtime/php/versions.ini
Labels: enhancement

#205 Add tests for the runtime layers
  .travis.yml
  composer.json
  phpunit.xml.dist
  tests/Sam/Php/function.php
  tests/Sam/PhpFpm/index.php
  tests/Sam/PhpFpmRuntimeTest.php
  tests/Sam/PhpRuntimeTest.php
  tests/Sam/template.yaml
Labels: enhancement

#207 Fix #191 and how the php.ini is dealt with
  docs/environment/php.md
  runtime/php/export.sh
  runtime/php/php.Dockerfile
  tests/Sam/PhpFpmRuntimeTest.php
  tests/Sam/PhpRuntimeTest.php
  tests/Sam/template.yaml
Labels: bug

#208 Disable logging above "warning" in PHP-FPM
  runtime/php/layers/fpm/php-fpm.conf
  tests/Runtime/PhpFpm/php-fpm.conf
Labels: bug

#209 Log exceptions and errors in PHP functions + add a truckload of tests
  phpstan.neon.dist
  src/Runtime/LambdaRuntime.php
  tests/Sam/Php/function.php
  tests/Sam/PhpFpm/index.php
  tests/Sam/PhpFpmRuntimeTest.php
  tests/Sam/PhpRuntimeTest.php
  tests/Sam/template.yaml
Labels: enhancement

#215 Update the Symfony documentation for 0.3
  docs/frameworks/symfony.md
  docs/runtimes/console.md
Labels: documentation

#216 Add tests to cover a bug where logs are forwarded in HTTP response headers
  src/Runtime/PhpFpm.php
  tests/Runtime/PhpFpm/error.php
  tests/Runtime/PhpFpmTest.php
  tests/Sam/PhpFpmRuntimeTest.php
Labels: bug

#218 Update the documentation for Laravel
  docs/frameworks/laravel.md
  docs/frameworks/symfony.md
Labels: documentation
