Repository brefphp/bref, pull requests merged in 2019-08, with the labels that each got.

#386 Add Tag parameter in makefile
  runtime/Makefile
Labels: enhancement

#395 Fix issue #394
  docs/runtimes/function.md
  template/default/index.php
Labels: bug

#392 Add command to start dashboard
  bref
  src/Console/LoadingAnimation.php
  src/Console/OpenUrl.php
Labels: enhancement

#398 Remove PHP-FPM from "function" layers
  runtime/Makefile
  runtime/layers/fpm/Dockerfile
  runtime/layers/function/Dockerfile
Labels: bug

#400 Fix the `docker pull` command: disable the timeout and show the correct error
  bref
Labels: bug

#403 Update documentation - fix link to 'Bref Docker images'
  docs/local-development.md
Labels: documentation

#411 Handle symfony in docker images
  runtime/layers/web/Dockerfile
  runtime/layers/web/default.conf
Labels: bug

#416 Add --host parameter to dashboard command (default is localhost)
  bref
Labels: enhancement

#417 Set workdir to /var/task
  runtime/layers/fpm/Dockerfile
  runtime/php-intermediary.Dockerfile
Labels: bug

#423 Doc: improve iamRoleStatements
  docs/environment/serverless-yml.md
Labels: documentation

#424 Add AWS profile option when using the dashboard
  bref
Labels: enhancement

#407 Change API Gateway/FPM timeouts to 28 seconds
  docs/frameworks/laravel.md
  docs/frameworks/symfony.md
  serverless.yml
  template/http/serverless.yml
Labels: bug, documentation

#431 docs: update database access from php
  docs/environment/database.md
Labels: documentation

#429 Add stage command option
  bref
Labels: enhancement

#435 Fix document typo
  docs/local-development.md
Labels: documentation

#440 Clarify text in the maturity matrix
  docs/README.md
Labels: documentation
