Repository brefphp/bref, pull requests merged in 2019-07, with the labels that each got.

#364 add MyBuilder workers to case studies page
  docs/case-studies.md
Labels: documentation

#360 Document the bref/logger package
  docs/environment/logs.md
Labels: documentation, enhancement

#354 Move from SAM to Serverless
  .gitignore
  Makefile
  bref
  couscous.yml
  docker-compose.yml
  docs/README.md
  docs/deploy.md
  docs/environment/database.md
  docs/environment/logs.md
  docs/environment/serverless-yml.md
  docs/environment/variables.md
  docs/first-steps.md
  docs/frameworks/laravel.md
  docs/frameworks/symfony.md
  docs/installation.md
  docs/installation/aws-keys-step-1.png
  docs/installation/aws-keys-step-2.png
  docs/installation/aws-keys.md
  docs/local-development.md
  docs/runtimes/README.md
  docs/runtimes/console.md
  docs/runtimes/function.md
  docs/runtimes/http.md
  index.js
  layers.json
  runtime/layer-list.php
  runtime/publish.php
  runtime/regions.json
  serverless.yml
  template.yaml
  template/console/serverless.yml
  template/console/template.yaml
  template/default/serverless.yml
  template/default/template.yaml
  template/http/serverless.yml
  template/http/template.yaml
Labels: enhancement

#268 Documentation for building websites
  couscous.yml
  docs/README.md
  docs/cloudfront.png
  docs/environment/custom-domains.md
  docs/runtimes/http.md
  docs/websites.md
  docs/websites/same-domain.svg
  docs/websites/separate-domains.svg
Labels: documentation

#371 Add Bref logo
  docs/readme-screenshot.png
  website/tailwind.js
  website/template/default.twig
  website/template/home.twig
  website/template/layout.twig
  website/template/logo.svg
  website/template/styles.css
Labels: documentation

#373 Update runtime to Amazon Linux 2018.03
  runtime/php/compiler.Dockerfile
  runtime/php/php.Dockerfile
  runtime/php/versions.ini
Labels: bug

#375 Add a useful link to Serverless case studies
  docs/case-studies.md
Labels: documentation

#376 Fix active page on the sidebar menu
  docs/README.md
  docs/case-studies.md
  docs/community.md
  docs/deploy.md
  docs/environment/custom-domains.md
  docs/environment/database.md
  docs/environment/logs.md
  docs/environment/php.md
  docs/environment/serverless-yml.md
  docs/environment/storage.md
  docs/environment/variables.md
  docs/first-steps.md
  docs/frameworks/laravel.md
  docs/frameworks/symfony.md
  docs/installation.md
  docs/local-development.md
  docs/newsletters.md
  docs/runtimes/README.md
  docs/runtimes/console.md
  docs/runtimes/function.md
  docs/runtimes/http.md
  docs/websites.md
Labels: documentation

#381 Escape remote CLI arguments
  bref
Labels: bug

#380 Remove tests and docs from php library directory
  runtime/php/php.Dockerfile
Labels: enhancement

#377 Increase function timeout for console applications
  template/console/serverless.yml
Labels: enhancement

#384 Update logs.md
  docs/environment/logs.md
Labels: documentation

#378 Compile php using GCC -O3
  runtime/php/php.Dockerfile
Labels: enhancement

#383 Run applications locally with Bref Docker images
  docs/local-development.md
  runtime/Makefile
  runtime/compiler.Dockerfile
  runtime/helpers/docker_args.sh
  runtime/layers/console/README.md
  runtime/layers/console/bootstrap
  runtime/layers/fpm-dev/Dockerfile
  runtime/layers/fpm-dev/php-fpm.conf
  runtime/layers/fpm/Dockerfile
  runtime/layers/fpm/bootstrap
  runtime/layers/fpm/php-fpm.conf
  runtime/layers/fpm/php.ini
  runtime/layers/function/Dockerfile
  runtime/layers/function/bootstrap
  runtime/layers/function/php.ini
  runtime/layers/web/Dockerfile
  runtime/layers/web/default.conf
  runtime/loop/README.md
  runtime/loop/bootstrap
  runtime/loop/build.sh
  runtime/loop/php.ini
  runtime/loop/publish.sh
  runtime/php-intermediary.Dockerfile
  runtime/php/Makefile
  runtime/php/export.sh
  runtime/php/readme.md
  runtime/versions.ini
Labels: enhancement
