Repository brefphp/bref, pull requests merged in 2019-10, with the labels that each got.

#471 Add an example artisan command
  docs/frameworks/laravel.md
Labels: documentation

#472 Update notice about cold starts
  docs/environment/database.md
Labels: documentation

#476 Add bref.dev short URLs
  bref
Labels: enhancement

#480 Report non-zero exit code as failure in the console layer
  demo/console.php
  runtime/layers/console/bootstrap
Labels: enhancement

#387 Documentation: Performances
  couscous.yml
  docs/environment/performances.md
  website/template/styles.css
Labels: documentation

#484 Add the XSL extension
  runtime/php-intermediary.Dockerfile
Labels: enhancement

#452 Added Imagick extension
  runtime/php-intermediary.Dockerfile
Labels: enhancement

#491 doc(php): add extensions Imagick and XSL
  docs/environment/php.md
Labels: documentation

#490 Refactor the build process
  docker-compose.yml
  docs/environment/php.md
  runtime/Makefile
  runtime/README.md
  runtime/base/README.md
  runtime/base/base.Dockerfile
  runtime/base/clean.sh
  runtime/base/php-72.Dockerfile
  runtime/base/php-73.Dockerfile
  runtime/compiler.Dockerfile
  runtime/helpers/docker_args.sh
  runtime/layers/fpm-dev/Dockerfile
  runtime/layers/fpm/Dockerfile
  runtime/layers/function/Dockerfile
  runtime/layers/layer-list.php
  runtime/layers/publish.php
  runtime/layers/regions.json
  runtime/layers/tests.php
  runtime/versions.ini
Labels: enhancement

#493 Fixed: No rule to make target 'build'.
  Makefile
Labels: bug

#494 Add strpos to contentType for response
  src/Runtime/LambdaRuntime.php
Labels: bug
