Repository brefphp/bref, pull requests merged in 2019-02, with the labels that each got.

#219 Add PHP 7.2 notice into documentation
  docs/installation.md
Labels: documentation

#221 remove typo in 'traditional'
  docs/README.md
Labels: documentation

#202 secret environment variables passed through in ci/cd pipeline
  docs/environment/variables.md
  docs/runtimes/README.md
Labels: documentation

#229 Cleanup Bref 0.2 classes
  composer.json
  src/Bridge/Laravel/LaravelAdapter.php
  src/Bridge/Psr7/RequestFactory.php
  src/Bridge/Slim/SlimAdapter.php
  src/Bridge/Symfony/SymfonyAdapter.php
  tests/Bridge/Laravel/LaravelAdapterTest.php
  tests/Bridge/Laravel/bootstrap/cache/.gitignore
  tests/Bridge/Laravel/config/app.php
  tests/Bridge/Laravel/storage/logs/.gitignore
  tests/Bridge/Psr7/RequestFactoryTest.php
  tests/Bridge/Slim/SlimAdapterTest.php
  tests/Bridge/Symfony/SymfonyAdapterTest.php
  tests/Bridge/Symfony/TestKernel.php
Labels: enhancement

#228 Bref's mission statement
  docs/README.md
Labels: documentation

#233 Allow to use Diactoros 2
  composer.json
Labels: enhancement

#238 Fix Bref CLI exit code
  bref
Labels: bug

#243 Add documentation for using custom domain names
  couscous.yml
  docs/environment/custom-domains-path-mapping.png
  docs/environment/custom-domains.md
  docs/runtimes/http.md
Labels: documentation

#244 Add anchors to documentation titles
  website/template/default.twig
Labels: documentation

#248 Publish runtime layer in eu-north-1 (Stockholm)
  runtime/publish.php
Labels: enhancement

#250 Recreate a new Responder every time because it contains state
  src/Runtime/PhpFpm.php
Labels: bug

#234 Set the memory size to 1024M by default for new lambdas
  template/console/template.yaml
  template/default/template.yaml
  template/http/template.yaml
Labels: enhancement

#225 Improve copying template files using init option
  bref
Labels: enhancement

#253 Fix #216 with a proper fix by upgrading hoa/fastcgi
  composer.json
  src/Runtime/PhpFpm.php
  tests/Runtime/PhpFpmTest.php
  tests/Sam/PhpFpmRuntimeTest.php
Labels: bug

#251 Fix #214 by disabling the `fastcgi_finish_request()` function
  runtime/php/layers/fpm/php.ini
Labels: bug

#245 Add page summary in the documentation
  website/template/default.twig
  website/template/styles.css
Labels: documentation
