Repository brefphp/bref, pull requests merged in 2019-05, with the labels that each got.

#323 tell the user to run aws configure when process exits
  bref
Labels: bug

#319 Migrate from hoa/fastcgi to hollodotme/fast-cgi-client
  composer.json
  src/Runtime/FastCgi/FastCgiCommunicationFailed.php
  src/Runtime/FastCgi/FastCgiRequest.php
  src/Runtime/PhpFpm.php
  tests/Performance/php-fpm.php
  tests/Runtime/PhpFpm/big-json.json
  tests/Runtime/PhpFpm/large-response.php
  tests/Runtime/PhpFpmTest.php
Labels: bug

#318 #316 Add a test to cover a bug with large responses
  tests/Runtime/PhpFpm/big-json.json
  tests/Runtime/PhpFpm/large-response.php
  tests/Runtime/PhpFpmTest.php
Labels: bug

#325 Adding limit to H1 in documentation
  website/template/styles.css
Labels: documentation

#335 Display the CloudFormation outputs in the `deployment` command
  bref
Labels: enhancement

#337 Update to latest runtimes
  docs/frameworks/laravel.md
  docs/frameworks/symfony.md
  template.yaml
  template/console/template.yaml
  template/default/template.yaml
  template/http/template.yaml
  tests/Sam/template.yaml
Labels: enhancement
