Repository brefphp/bref, pull requests merged in 2019-09, with the labels that each got.

#444 Fall back to parent functions for Symfony Kernel
  docs/frameworks/symfony.md
Labels: documentation

#430 Add a warning when installing Bref
  docs/installation.md
Labels: documentation

#442 Home page
  Makefile
  couscous.yml
  docs/README.md
  website/package-lock.json
  website/package.json
  website/tailwind.config.js
  website/tailwind.js
  website/template/default.twig
  website/template/home.twig
  website/template/img/aws.svg
  website/template/img/logo-white.svg
  website/template/layout.twig
  website/template/logo.svg
  website/template/styles.css
  website/yarn.lock
Labels: documentation

#445 Fixed typo
  docs/frameworks/symfony.md
Labels: documentation

#396 Enable GD extension
  runtime/php-intermediary.Dockerfile
Labels: enhancement

#449 fix doc about cold starts
  docs/README.md
Labels: documentation

#462 Fix #461 Build the fpm-dev images from the lambci images
  runtime/layers/fpm-dev/Dockerfile
Labels: bug

#451 Update the maturity matrix
  docs/README.md
Labels: documentation

#466 Allow region to be a variable
  index.js
Labels: bug

#457 Handle binary responses (encode body)
  src/Runtime/LambdaRuntime.php
Labels: enhancement

#467 Fix php-7*-fpm-dev images that were missing php.ini
  demo/http.php
  runtime/Makefile
  runtime/layers/fpm-dev/Dockerfile
  runtime/layers/fpm-dev/php-fpm.conf
Labels: bug
