Repository brefphp/bref, pull requests merged in 2019-04, with the labels that each got.

#289 Enable SOAP
  runtime/php/php.Dockerfile
Labels: enhancement

#299 Update runtimes by adding more extensions and fixing stuff
  docs/environment/php.md
  docs/frameworks/laravel.md
  docs/frameworks/symfony.md
  runtime/php/layers/fpm/php.ini
  runtime/php/layers/function/php.ini
  runtime/php/php.Dockerfile
  src/Runtime/LambdaRuntime.php
  template.yaml
  template/console/template.yaml
  template/default/template.yaml
  template/http/template.yaml
  tests/Sam/Php/function.php
  tests/Sam/PhpFpm/index.php
  tests/Sam/PhpFpmRuntimeTest.php
  tests/Sam/PhpRuntimeTest.php
  tests/Sam/template.yaml
Labels: enhancement

#293 #292 Enable bcmath extension
  runtime/php/php.Dockerfile
Labels: enhancement

#298 reuse curl handler
  src/Runtime/LambdaRuntime.php
Labels: enhancement

#297 Add content length header for more http methods
  src/Runtime/PhpFpm.php
  tests/Runtime/PhpFpmTest.php
Labels: bug

#305 Adjust alt-text in README.md to match image content
  README.md
Labels: documentation

#307 Enable socketsets
  runtime/php/php.Dockerfile
Labels: enhancement

#308 Add a new `bref deployment` command to debug failed deployments
  bref
  docs/deploy.md
Labels: enhancement

#311 Pass the Lambda context to handlers
  src/Context/Context.php
  src/Context/ContextBuilder.php
  src/Runtime/LambdaRuntime.php
  tests/Context/ContextBuilderTest.php
  tests/Runtime/LambdaRuntimeTest.php
Labels: enhancement

#321 Avoid dump logs
  runtime/php/layers/fpm/php-fpm.conf
Labels: bug
