Repository brefphp/bref, pull requests merged in 2019-11, with the labels that each got.

#499 add test to check if extensions are loadable
  runtime/helpers/extensions-test.sh
  runtime/helpers/php/conf.d/php.ini
  runtime/layers/tests.php
Labels: enhancement

#498 Add xdebug to php-fpm-dev container
  docs/local-development.md
  runtime/layers/fpm-dev/Dockerfile
  runtime/layers/fpm-dev/php-fpm.conf
Labels: enhancement

#488 Add blackfire probe extension to fpm-dev container
  docs/local-development.md
  runtime/layers/fpm-dev/Dockerfile
Labels: enhancement

#502 add test to check if development extensions have been loaded
  runtime/helpers/php/conf.dev.d/php.ini
  runtime/layers/tests.php
Labels: enhancement

#503 Add additional AWS regions to database docs
  docs/environment/database.md
Labels: documentation

#504 Fix fpm-dev-gateway
  runtime/layers/web/default.conf
Labels: enhancement

#505 Encode body responses in base64 only when configured
  docs/runtimes/http.md
  src/Http/LambdaResponse.php
  src/Runtime/LambdaRuntime.php
Labels: bug

#507 Improve error message when returning binary responses
  src/Runtime/LambdaRuntime.php
  tests/Runtime/LambdaRuntimeTest.php
Labels: enhancement

#508 Small improvements to the documentation
  docs/deploy.md
  docs/frameworks/symfony.md
  docs/websites.md
Labels: documentation

#511 added support for symfony 5
  composer.json
Labels: enhancement

#514 Add test suite to composer
  composer.json
Labels: enhancement

#515 Improve the documentation regarding VPCs
  docs/environment/database.md
Labels: documentation
