Repository brefphp/bref, pull requests merged in 2020-03, with the labels that each got.

#575 Use AsyncAws instead of AWS SDK
  bref
  composer.json
  runtime/layers/layer-list.php
  src/Lambda/InvocationResult.php
  src/Lambda/SimpleLambdaClient.php
Labels: enhancement

#580 Update case-studies.md
  docs/case-studies.md
Labels: documentation

#582 Migrate example to AsyncAws
  docs/runtimes/function.md
Labels: documentation

#577 Remove decorate_workers_output from php-fpm.conf
  runtime/layers/fpm/Dockerfile
  runtime/layers/fpm/php-fpm.conf
Labels: enhancement

#585 replace defective anchor
  docs/runtimes/http.md
Labels: documentation

#568 Update docs to reflect Laravel 6. fixes #528
  docs/frameworks/laravel.md
Labels: documentation

#590 Cloudwatch logs formatted similar to native Runtime, v2
  src/Runtime/LambdaRuntime.php
  tests/Handler/FpmHandlerTest.php
  tests/Runtime/LambdaRuntimeTest.php
  tests/Sam/PhpRuntimeTest.php
Labels: enhancement

#591 Update composer.json
  composer.json
Labels: enhancement

#593 [PHP-FPM configuration] Increase log_limit
  runtime/layers/fpm/Dockerfile
  runtime/layers/fpm/php-fpm.conf
Labels: bug

#595 Add support for EventBridge events
  src/Event/EventBridge/EventBridgeEvent.php
  src/Event/EventBridge/EventBridgeHandler.php
  tests/Event/EventBridge/EventBridgeEventTest.php
  tests/Event/EventBridge/eventbridge-details-empty.json
  tests/Event/EventBridge/eventbridge.json
  tests/Runtime/LambdaRuntimeTest.php
Labels: enhancement

#598 Use PHP 7.4.4
  runtime/base/php-74.Dockerfile
Labels: enhancement

#600 Fix #599 Set up the same "max upload size" in PHP as API Gateway/Lambda
  Makefile
  phpstan.neon.dist
  phpunit.xml.dist
  runtime/layers/fpm/php.ini
  runtime/layers/web/default.conf
  tests/Functional/FpmRuntimeTest.php
  tests/Functional/fpm/index.php
  tests/Sam/PhpFpmRuntimeTest.php
  tests/serverless.tests.yml
Labels: enhancement
