Repository brefphp/bref, pull requests merged in 2020-01, with the labels that each got.

#525 Updated Symfony section to support serverless.
  docs/frameworks/symfony.md
Labels: documentation

#524 Fix boolean type casting
  src/Runtime/LambdaRuntime.php
Labels: bug

#519 Tag docker images when tag on Github
  .github/workflows/deploy-docker.yml
  Makefile
Labels: enhancement

#529 Added documentation for enabling the GD extension
  docs/environment/php.md
Labels: documentation

#530 Fix serverless-yml.md runtime usage href link
  docs/environment/serverless-yml.md
Labels: documentation

#532 Update docs to also reflect binary requests/uploads
  docs/runtimes/http.md
Labels: documentation

#539 Fix broken master build
  tests/Runtime/PhpFpmTest.php
Labels: bug

#540 Turn Handler interfaces into abstract classes
  phpstan.neon.dist
  src/Event/Http/FpmHandler.php
  src/Event/Http/HttpHandler.php
  src/Event/Http/Psr15Handler.php
  src/Event/S3/S3Handler.php
  src/Event/Sqs/SqsHandler.php
  src/Runtime/LambdaRuntime.php
  tests/Runtime/LambdaRuntimeTest.php
Labels: enhancement

#543 Add event and context to the Psr15Handler request
  src/Event/Http/Psr15Handler.php
  tests/Runtime/LambdaRuntimeTest.php
Labels: enhancement

#542 Rebase: Expose the request context in the FPM layer via a global variable
  src/Event/Http/FpmHandler.php
  src/Event/Http/HttpRequestEvent.php
  tests/Handler/FpmHandlerTest.php
Labels: enhancement

#545 Fix error reporting configuration for PHP 7.4
  runtime/layers/fpm/php.ini
  runtime/layers/function/php.ini
Labels: bug

#527 Use PHP 7.4.2
  runtime/base/php-74.Dockerfile
Labels: enhancement

#544 Add SNS event handler support
  src/Event/Sns/MessageAttribute.php
  src/Event/Sns/SnsEvent.php
  src/Event/Sns/SnsHandler.php
  src/Event/Sns/SnsRecord.php
  tests/Event/Sns/SnsEventTest.php
  tests/Event/Sns/sns.json
  tests/Runtime/LambdaRuntimeTest.php
Labels: enhancement
