Repository brefphp/bref, pull requests merged in 2020-08, with the labels that each got.

#707 Add request_terminate_timeout = 27s
  runtime/layers/fpm/php-fpm.conf
  runtime/layers/fpm/php.ini
Labels: enhancement

#706 bump PHP versions
  runtime/base/php-72.Dockerfile
  runtime/base/php-73.Dockerfile
  runtime/base/php-74.Dockerfile
Labels: enhancement

#693 Handle ALB Multivalue Request
  src/Event/Http/FpmHandler.php
  src/Event/Http/HttpRequestEvent.php
  tests/Handler/FpmHandlerLoadBalancerTest.php
  tests/Handler/PhpFpm/alb-multi-value-query-string-encoded.json
  tests/Handler/PhpFpm/alb-multi-value-query-string-with-numeric-keys.json
  tests/Handler/PhpFpm/alb-multi-value-query-string.json
  tests/Handler/PhpFpm/alb-query-string-encoded.json
  tests/Handler/PhpFpm/alb-query-string-mixed-encoding.json
  tests/Handler/PhpFpm/alb-query-string.json
Labels: enhancement

#712 Improve the Laravel documentation regarding caching
  docs/frameworks/laravel.md
Labels: documentation

#714 Remove request_terminate_timeout = 27s
  runtime/layers/fpm/php-fpm.conf
Labels: bug

#717 Bump php 8 version
  runtime/base/php-80.Dockerfile
Labels: enhancement

#724 Add getter for ReceiptHandle in SQSRecord
  src/Event/Sqs/SqsRecord.php
  tests/Event/Sqs/SqsEventTest.php
Labels: enhancement
