Repository brefphp/bref, pull requests merged in 2020-11, with the labels that each got.

#779 docs: AWS new interface for API gateway and custom domains
  docs/environment/custom-domains-path-mapping.png
  docs/environment/custom-domains.md
Labels: documentation

#780 Update websites.md
  docs/websites.md
Labels: documentation

#774 Update gd extension reference
  docs/environment/php.md
Labels: documentation

#782 #650 Recover from broken PHP-FPM by restarting the process
  src/Event/Http/FpmHandler.php
Labels: bug

#773 Add typed ApiGateway websocket events
  src/Event/ApiGateway/WebsocketEvent.php
  src/Event/ApiGateway/WebsocketHandler.php
  tests/Event/ApiGateway/WebsocketEventTest.php
  tests/Event/ApiGateway/websocket-connect.json
  tests/Event/ApiGateway/websocket-disconnect.json
  tests/Event/ApiGateway/websocket-message.json
Labels: enhancement

#785 #409 Add a `bref local` command to invoke functions locally
  bref
  composer.json
  demo/function.php
  docs/environment/variables.md
  docs/local-development.md
  src/Console/Command/Local.php
  src/Runtime/FileHandlerLocator.php
  src/Runtime/Invoker.php
  src/Runtime/LambdaRuntime.php
Labels: enhancement

#788 fix: missing amazon linux 2 lib
  runtime/base/base.Dockerfile
Labels: bug

#789 chore: upgrade libraries for bref 1.0
  runtime/base/base.Dockerfile
  runtime/base/php-74.Dockerfile
  runtime/base/php-80.Dockerfile
Labels: enhancement

#792 Feature/config local run
  src/Console/Command/Local.php
Labels: enhancement

#795 Remove the deprecated `lambda()` function
  composer.json
  docs/upgrade/1.0.md
  src/functions.php
Labels: enhancement

#791 Reorganize the documentation to separate "Bref for web apps" and "Bref for functions"
  bref
  couscous.yml
  docs/README.md
  docs/cron.md
  docs/deploy.md
  docs/environment/custom-domains.md
  docs/environment/logs.md
  docs/environment/performances.md
  docs/first-steps.md
  docs/frameworks/symfony.md
  docs/function/cron.md
  docs/function/handlers.md
  docs/function/local-development.md
  docs/installation.md
  docs/runtimes/README.md
  docs/runtimes/console.md
  docs/runtimes/function.md
  docs/runtimes/http.md
  docs/web-apps/cron.md
  docs/web-apps/edge-deployment.png
  docs/web-apps/local-development.md
  docs/websites.md
  runtime/layers/publish.php
  src/Console/Command/Local.php
  src/Runtime/LambdaRuntime.php
  template/console/serverless.yml
  template/function/index.php
  template/function/serverless.yml
  template/http/serverless.yml
  tests/Runtime/LambdaRuntimeTest.php
  website/package-lock.json
  website/tailwind.config.js
  website/template/_redirects
  website/template/default.twig
  website/template/home.twig
  website/template/styles.css
Labels: documentation

#794 #309 Include the stage prefix in the URL
  src/Event/Http/HttpRequestEvent.php
  tests/Event/Http/CommonHttpTest.php
  tests/Event/Http/Fixture/ag-v1-stage-prefix.json
  tests/Handler/FpmHandlerTest.php
Labels: bug

#796 Remove obsolete bref.dev command
  bref
  docs/upgrade/1.0.md
Labels: enhancement

#797 Remove the bref deployment command
  bref
  composer.json
Labels: enhancement

#597 Suggest to exclude var directory when deploying Symfony applications
  docs/frameworks/symfony.md
Labels: documentation

#799 Re-remove the API Gateway stage prefix from URLs
  src/Event/Http/HttpRequestEvent.php
  tests/Event/Http/CommonHttpTest.php
  tests/Handler/FpmHandlerTest.php
Labels: bug

#802 chore: upgrade to latest php versions
  runtime/base/php-73.Dockerfile
  runtime/base/php-74.Dockerfile
  runtime/base/php-80.Dockerfile
Labels: enhancement

#805 Expose API Gateway path parameters
  docs/function/handlers.md
  src/Event/Http/HttpRequestEvent.php
  src/Event/Http/Psr7Bridge.php
  tests/Event/Http/CommonHttpTest.php
  tests/Event/Http/Fixture/ag-v1-path-parameters.json
  tests/Event/Http/Fixture/ag-v2-path-parameters.json
  tests/Event/Http/HttpRequestEventTest.php
  tests/Event/Http/Psr7BridgeTest.php
Labels: enhancement

#806 Local - Parse config tags, prevent from crashing
  src/Console/Command/Local.php
Labels: enhancement
