Repository brefphp/bref, pull requests merged in 2020-05, with the labels that each got.

#643 Add Cape Town Region
  runtime/layers/regions.json
Labels: enhancement

#644 added new region milan
  runtime/layers/regions.json
Labels: enhancement

#651 Indentation problem
  docs/case-studies.md
Labels: documentation

#654 Enable the PDO MySQL extension by default
  docs/environment/php.md
  runtime/layers/fpm/php.ini
  runtime/layers/function/php.ini
Labels: enhancement

#640 Add Kinesis typed events
  src/Event/Kinesis/KinesisEvent.php
  src/Event/Kinesis/KinesisHandler.php
  src/Event/Kinesis/KinesisRecord.php
  tests/Event/Kinesis/KinesisEventTest.php
  tests/Event/Kinesis/kinesis.json
Labels: enhancement

#645 Don't kill self
  src/Event/Http/FpmHandler.php
Labels: bug

#657 Update composer.json
  composer.json
Labels: enhancement

#659 Update message Attributes
  tests/Event/Sqs/SqsEventTest.php
  tests/Event/Sqs/sqs.json
Labels: bug
