Repository brefphp/bref, pull requests merged in 2020-04, with the labels that each got.

#605 Updated tests
  tests/Handler/FpmHandlerTest.php
  tests/Runtime/LambdaRuntimeTest.php
  tests/Sam/PhpFpmRuntimeTest.php
  tests/Sam/Psr7Test.php
Labels: enhancement

#610 Add details about setting SSM entries on Windows
  docs/environment/variables.md
Labels: documentation

#611 Homepage Type Updates
  website/template/home.twig
Labels: documentation

#603 add reference to the rds-data api (resolves #596)
  docs/environment/database.md
Labels: documentation

#606 try to make the cdn configuration simpler
  docs/websites.md
Labels: documentation

#614 Bump Version of AsyncAWS
  bref
  composer.json
Labels: enhancement

#618 Fix missing dependency for PSR-15 handlers
  composer.json
  src/Event/Http/Psr7Bridge.php
Labels: bug

#561 Add DynamoDB typed events
  docs/runtimes/function.md
  src/Event/DynamoDb/DynamoDbEvent.php
  src/Event/DynamoDb/DynamoDbHandler.php
  src/Event/DynamoDb/DynamoDbRecord.php
  tests/Event/DynamoDb/DynamoDbEventTest.php
  tests/Event/DynamoDb/dynamodb.json
Labels: enhancement

#623 Revise Lambda/Request context within PHP-FPM handler
  docs/runtimes/http.md
  src/Context/Context.php
  src/Event/Http/FpmHandler.php
  tests/Handler/FpmHandlerTest.php
Labels: enhancement

#626 Expose Lambda invocation context within console runtime
  docs/runtimes/console.md
  runtime/layers/console/bootstrap
Labels: enhancement

#615 Simplify the console invocation format (use a simple string)
  bref
  runtime/layers/console/bootstrap
Labels: enhancement

#627 Improve the Laravel documentation (config and Laravel Passport)
  docs/frameworks/laravel.md
Labels: documentation

#628 Update the documentation: the `--docker` flag is not needed anymore
  docs/environment/variables.md
  docs/local-development.md
Labels: documentation

#634 New behaviour for config caches in Laravel 7.x
  docs/frameworks/laravel.md
Labels: documentation

#637 Remove the timeout on `bref cli`
  bref
  demo/console.php
  serverless.yml
  src/Lambda/SimpleLambdaClient.php
Labels: bug

#635 Continue to improve the Laravel documentation
  docs/frameworks/laravel.md
Labels: documentation
