Repository brefphp/bref, pull requests merged in 2020-06, with the labels that each got.

#662 fix: prefer not using getenv
  docs/frameworks/symfony.md
Labels: documentation

#668 Fix #118 Document Laravel Queues, along with Symfony Messenger
  docs/README.md
  docs/frameworks/laravel.md
  docs/frameworks/symfony.md
Labels: documentation

#670 Default HTTP request event version to 1.0
  src/Event/Http/HttpRequestEvent.php
Labels: bug

#673 Use version 1.0 of AsyncAws deps
  composer.json
Labels: enhancement

#674 Add very basic analytics via a ping
  src/Runtime/LambdaRuntime.php
Labels: enhancement
