Repository brefphp/bref, pull requests merged in 2020-09, with the labels that each got.

#729 Fix typo
  couscous.yml
  docs/README.md
  docs/case-studies.md
  docs/environment/database.md
  docs/environment/performance.md
  docs/environment/serverless-yml.md
  docs/websites.md
  website/template/enterprise.twig
Labels: documentation

#672 Added support for multi-value query parameters
  src/Event/Http/HttpRequestEvent.php
  tests/Event/Http/CommonHttpTest.php
  tests/Event/Http/Fixture/ag-v1-query-string-multivalue.json
  tests/Event/Http/Fixture/ag-v2-query-string-multivalue.json
  tests/Handler/FpmHandlerTest.php
Labels: enhancement

#730 Add a `bref layers` command
  bref
Labels: enhancement

#731 Document BREF_AUTOLOAD_PATH
  docs/environment/php.md
Labels: documentation

#737 Fixing a bunch of links into the PHP docs
  docs/environment/php.md
Labels: documentation

#736 Fix fpm dev gateway
  runtime/layers/web/Dockerfile
  runtime/layers/web/default.conf
Labels: enhancement

#739 Removing broken link
  docs/environment/php.md
Labels: documentation

#702 Remove `enable-maintainer-zts`
  runtime/base/php-72.Dockerfile
  runtime/base/php-73.Dockerfile
  runtime/base/php-74.Dockerfile
  runtime/base/php-80.Dockerfile
Labels: enhancement

#742 Remove support for PHP 7.2
  .travis.yml
  Makefile
  composer.json
  docs/installation.md
  docs/runtimes/README.md
  layers.json
  runtime/Makefile
  runtime/base/php-72.Dockerfile
  runtime/layers/fpm/Dockerfile
  runtime/layers/fpm/php-fpm.conf
  runtime/layers/layer-list.php
  runtime/layers/publish.php
  runtime/layers/tests.php
  tests/Event/Sns/SnsEventTest.php
Labels: enhancement

#745 Upgrade static analysis tools
  .phpcs.xml.dist
  .prettyci.composer.json
  composer.json
  src/Context/Context.php
  src/Event/Http/FpmHandler.php
  src/Runtime/LambdaRuntime.php
  tests/Event/Http/Psr7BridgeTest.php
  tests/Functional/FpmRuntimeTest.php
  tests/Runtime/LambdaRuntimeTest.php
  tests/Sam/PhpFpmRuntimeTest.php
  tests/Sam/PhpRuntimeTest.php
  tests/Server.php
Labels: enhancement

#748 fix: shell typo in nghttp2 build script
  runtime/base/base.Dockerfile
Labels: bug

#749 doc: remove pthread mentions
  docs/environment/php.md
Labels: documentation

#753 chore: remove imagick extension
  docs/environment/php.md
  runtime/base/base.Dockerfile
  runtime/base/php-73.Dockerfile
  runtime/base/php-74.Dockerfile
  runtime/base/php-80.Dockerfile
Labels: enhancement

#751 Update database.md, added public IP limitation of Aurora Serverless.
  docs/environment/database.md
Labels: documentation

#760 Fix typo in "PHP functions"
  docs/runtimes/function.md
Labels: documentation

#694 Add native support for providing handlers from PSR-11 containers
  composer.json
  runtime/layers/function/bootstrap.php
  src/Bref.php
  src/Runtime/FileHandlerLocator.php
  src/Runtime/HandlerNotFound.php
  tests/BrefTest.php
  tests/Runtime/FileHandlerLocatorTest.php
  tests/Runtime/Fixtures/broken.php
  tests/Runtime/Fixtures/foo.php
Labels: enhancement

#750 bump PHP version
  runtime/base/php-73.Dockerfile
  runtime/base/php-74.Dockerfile
Labels: enhancement

#761 Remove deprecated `bref invoke` command
  bref
Labels: enhancement

#762 add dynamo db cache bundle to readme
  docs/frameworks/symfony.md
Labels: documentation

#754 Move the gd extension into a separate layer
  docs/environment/php.md
  runtime/base/base.Dockerfile
  runtime/base/php-73.Dockerfile
  runtime/base/php-74.Dockerfile
  runtime/base/php-80.Dockerfile
  tests/Sam/PhpRuntimeTest.php
Labels: enhancement
