Repository brefphp/bref, pull requests merged in 2020-10, with the labels that each got.

#765 Fix typo
  src/Runtime/LambdaRuntime.php
Labels: documentation

#772 Remove Socket Timeout from FPM Layer
  src/Event/Http/FpmHandler.php
Labels: bug

#775 Migrate to Amazon Linux 2 images
  docs/environment/php.md
  docs/environment/serverless-yml.md
  docs/frameworks/symfony.md
  docs/runtimes/README.md
  docs/runtimes/console.md
  docs/runtimes/function.md
  docs/runtimes/http.md
  docs/websites.md
  runtime/Makefile
  runtime/base/base.Dockerfile
  runtime/base/clean.sh
  runtime/base/php-73.Dockerfile
  runtime/base/php-74.Dockerfile
  runtime/base/php-80.Dockerfile
  runtime/layers/fpm-dev/Dockerfile
  runtime/layers/fpm/Dockerfile
  runtime/layers/function/Dockerfile
  runtime/layers/publish.php
  runtime/layers/tests.php
  serverless.yml
  template/console/serverless.yml
  template/default/serverless.yml
  template/http/serverless.yml
  tests/Sam/template.yaml
  tests/serverless.tests.yml
Labels: enhancement

#778 Install cmake3 from yum in AL2
  runtime/base/base.Dockerfile
Labels: enhancement
