Repository brefphp/bref, pull requests merged in 2021-09, with the labels that each got.

#1010 Update php8.1 to use RC1
  runtime/base/php-81.Dockerfile
Labels: enhancement

#1009 Document event/context for PSR-15 handlers
  docs/function/handlers.md
Labels: documentation

#1014 [Docs] Document server-side construct in Symfony docs
  docs/frameworks/symfony.md
Labels: documentation

#1026 Function runtime: force restarting the process for failed invocations
  docs/environment/performances.md
  runtime/layers/function/bootstrap.php
  src/Runtime/LambdaRuntime.php
  tests/Runtime/LambdaRuntimeTest.php
Labels: enhancement

#1013 Let LambdaRuntime::processNextEvent() return boolean
  src/Runtime/LambdaRuntime.php
  tests/Runtime/LambdaRuntimeTest.php
Labels: enhancement

#1020 Understand file include notation
  src/Console/Command/Local.php
Labels: bug

#1027 Upgrade to PHP 8.1.0RC2
  runtime/base/php-81.Dockerfile
Labels: enhancement

#1030 Upgrade to openssl `1.1.1l`
  runtime/base/base.Dockerfile
Labels: enhancement, runtime

#1031 Collect which layer was used for invocation
  runtime/layers/console/bootstrap
  runtime/layers/fpm/bootstrap
  runtime/layers/function/bootstrap.php
  runtime/ping/statsd.config.json
  src/Runtime/LambdaRuntime.php
  tests/Runtime/LambdaRuntimeTest.php
Labels: enhancement, runtime
