Repository brefphp/bref, pull requests merged in 2021-08, with the labels that each got.

#976 Fixes #975 Copied breftoolbox.php to layer
  runtime/layers/console/Dockerfile
Labels: bug

#996 Support for events without size attribute
  src/Event/S3/S3Record.php
  tests/Event/S3/S3EventTest.php
  tests/Event/S3/s3-object-removed.json
Labels: bug

#998 Remove init command for console apps in the docs
  docs/runtimes/console.md
Labels: documentation

#993 Improve automation of PHP Builder Layers
  Makefile
  composer.json
  runtime/layers/layer-list.php
  runtime/pipeline/builder.yaml
  runtime/pipeline/buildspec.yaml
Labels: enhancement, runtime

#985 Bumped PHP versions
  runtime/base/php-74.Dockerfile
  runtime/base/php-80.Dockerfile
Labels: enhancement, runtime

#980 PHP 8.1 runtimes
  docs/runtimes/README.md
  runtime/Makefile
  runtime/base/php-81.Dockerfile
  runtime/layers/layer-list.php
  runtime/layers/publish.php
  runtime/layers/tests.php
Labels: enhancement, runtime

#1007 feat(runtimes): build and publish PHP 8.1 docker images
  Makefile
  runtime/Makefile
  runtime/layers/fpm-dev/Dockerfile
  runtime/layers/tests.php
Labels: enhancement
