Repository brefphp/bref, pull requests merged in 2021-01, with the labels that each got.

#830 use new amazon container images
  Makefile
  docs/environment/php.md
  runtime/Makefile
  runtime/base/base.Dockerfile
  runtime/base/php-73.Dockerfile
  runtime/base/php-74.Dockerfile
  runtime/base/php-80.Dockerfile
  runtime/layers/fpm/Dockerfile
  runtime/layers/function/Dockerfile
Labels: enhancement

#812 Allow separation and lazy loading of vendor folder in s3
  docs/environment/php.md
  index.js
  runtime/layers/console/bootstrap
  runtime/layers/console/breftoolbox.php
  runtime/layers/fpm/Dockerfile
  runtime/layers/fpm/bootstrap
  runtime/layers/fpm/breftoolbox.php
  runtime/layers/function/Dockerfile
  runtime/layers/function/bootstrap.php
  runtime/layers/function/breftoolbox.php
Labels: enhancement

#835 Re-enable opcache.validate_timestamps
  runtime/layers/fpm/php.ini
  runtime/layers/function/php.ini
Labels: bug

#838 Fix Documentation Serverless GetAtt syntax error
  docs/frameworks/laravel.md
Labels: documentation

#839 Remove chalk
  index.js
Labels: bug

#841 Support multiple cookies with API Gateway v2
  demo/psr7.php
  serverless.yml
  src/Event/Http/FpmHandler.php
  src/Event/Http/HttpHandler.php
  src/Event/Http/HttpRequestEvent.php
  src/Event/Http/HttpResponse.php
  tests/Event/Http/HttpResponseTest.php
  tests/Functional/HttpApiTest.php
  tests/Functional/http-api/index.php
  tests/serverless.tests.yml
Labels: enhancement

#843 Fixed docker entrypoint in documentation
  docs/function/local-development.md
Labels: documentation

#848 initialize provider environment variables if there are none
  index.js
Labels: bug

#851 clarify documentation concerning separate vendor folder
  docs/environment/php.md
Labels: documentation

#852 Billed duration is now the same as duration when invoking function from `bref local`
  src/Console/Command/Local.php
Labels: enhancement

#853 Updated PDO-Sqlite link to go to the correct page.
  docs/environment/php.md
Labels: documentation
