Repository brefphp/bref, pull requests merged in 2021-04, with the labels that each got.

#903 Send console output to CloudWatch in real time
  runtime/layers/console/bootstrap
Labels: enhancement

#906 Update console.md
  docs/runtimes/console.md
Labels: documentation

#905 Curl security update
  runtime/base/base.Dockerfile
Labels: enhancement

#909 #908 Support the new Serverless plugin variables introduced in 20210326
  index.js
Labels: bug

#912 Upgrade blackfire in fpm-dev image
  runtime/layers/fpm-dev/Dockerfile
Labels: enhancement

#915 [Docs] Update AWS CLI S3 sync command to v2
  docs/websites.md
Labels: documentation

#916 [Docs] Update Laravel documentation references to automatically point to latest version
  docs/frameworks/laravel.md
  docs/runtimes/README.md
  docs/runtimes/console.md
  docs/web-apps/local-development.md
Labels: documentation
