Repository brefphp/bref, pull requests merged in 2021-03, with the labels that each got.

#871 Document S3 assets deployment for Symfony
  docs/frameworks/symfony.md
Labels: documentation

#874 Document using buildDir in Kernel.php
  docs/frameworks/symfony.md
Labels: documentation

#872 Document trusted_proxies & trusted_headers for Symfony
  docs/frameworks/symfony.md
Labels: documentation

#877 Bumped PHP versions to latest patch version
  runtime/base/php-73.Dockerfile
  runtime/base/php-74.Dockerfile
  runtime/base/php-80.Dockerfile
Labels: enhancement

#886 Update path to cacert.pem
  runtime/base/base.Dockerfile
Labels: bug

#887 Test build docker images on PRs
  .github/workflows/build-docker.yml
Labels: enhancement

#891 fix: docker push
  Makefile
Labels: bug

#896 Upgraded base dependencies to patch security issues
  runtime/base/base.Dockerfile
Labels: enhancement

#898 Fix typos
  docs/runtimes/README.md
Labels: documentation

#902 [FPM] Update comment and max_execution_time
  runtime/layers/fpm/php.ini
Labels: enhancement
