Repository brefphp/bref, pull requests merged in 2023-11, with the labels that each got.

#1683 (Docs) Added information on the deployment docs for reducing deployment size when using aws/google SDKs
  docs/deploy.mdx
Labels: documentation

#1690 Add ability to get queue name from sqs event
  src/Event/Sqs/SqsRecord.php
  tests/Event/Sqs/SqsRecordTest.php
Labels: enhancement

#1695 Fix "internal error" on invalid cookies
  src/Event/Http/HttpRequestEvent.php
  tests/Event/Http/CommonHttpTest.php
  tests/Event/Http/Fixture/ag-v1-cookies-invalid.json
  tests/Event/Http/Fixture/ag-v2-cookies-invalid.json
  tests/Event/Http/HttpRequestEventTest.php
  tests/Event/Http/Psr7BridgeTest.php
  tests/FpmRuntime/FpmHandlerTest.php
  tests/HttpRequestProxyTest.php
Labels: bug
