Repository brefphp/bref, pull requests merged in 2023-03, with the labels that each got.

#1422 Add "monitoring" documentation with Bref Dashboard and Tideways
  couscous.yml
  docs/monitoring.md
  docs/monitoring/bref-dashboard.png
  docs/monitoring/tideways-schema.svg
  website/template/home.twig
  website/template/img/logo-tideways.svg
Labels: documentation

#1438 Remove GeckoEngage sponsor
  website/template/home.twig
  website/template/img/logo-gecko-engage.png
Labels: documentation

#1442 Fix bref console bootstrap if using old versions of symfony/process
  runtime/layers/console/bootstrap
Labels: bug

#1448 Support `runtime: php-81` in Lift constructs
  index.js
Labels: bug

#1424 Update the Laravel docs for v2
  docs/frameworks/laravel.md
Labels: documentation

#1443 Add v2.0 blog post
  docs/news/02-bref-2.0.md
  docs/news/02/executions.png
  docs/news/02/social-card.png
  docs/news/README.md
  docs/upgrading/v2.md
  website/template/layout.twig
  website/template/news-article.twig
  website/template/news.twig
Labels: documentation

#1462 Fix #1461 Partial failures behavior broken with v2
  src/Event/Sqs/SqsHandler.php
  tests/Event/Sqs/SqsEventTest.php
  tests/Event/Sqs/SqsHandlerTest.php
  tests/Fixture/SqsFakeHandler.php
Labels: bug

#1483 Improve the error message when returning a payload above the Lambda limits
  demo/function.php
  demo/http.php
  serverless.yml
  src/Runtime/LambdaRuntime.php
  src/Runtime/ResponseTooBig.php
  tests/Runtime/LambdaRuntimeTest.php
Labels: bug

#1482 Improve error message when missing Bref runtimes
  src/Event/InvalidLambdaEvent.php
  tests/Event/EventBridge/EventBridgeEventTest.php
  tests/Event/Http/HttpRequestEventTest.php
  tests/Event/Kafka/KafkaEventTest.php
  tests/Event/S3/S3EventTest.php
  tests/Event/Sns/SnsEventTest.php
  tests/Event/Sqs/SqsEventTest.php
Labels: enhancement
